### ISSUE TITLE
Set language to translate to

### ISSUE THREAD

**Issue by loopernow** [shana0440/inline-translator#1]
Hello; I installed your extension on Firefox. How can I set what language to translate to?

**Comment by shana0440** [comment]
Hi, I didn't provide any way to set the target language.
You can try another extension called "Immersive Translate," which can perform the same function and better.
https://addons.mozilla.org/en-US/firefox/addon/immersive-translate/

**Comment by loopernow** [comment]
Hmm, thank you, but yours is only a few KB and open-source, and that one is nearly 4 MB and closed-source! Thank you though.

**Comment by shana0440** [comment]
Support setting the language that translate to at version 0.1.0.
@loopernow you can update the extension from firefox add-ons store if you still waiting for this feature.
feel free to open this issue if still have problem with setting the language that translate to.

**Comment by loopernow** [comment]
Thank you; this is really great! :)
