### ISSUE TITLE
Update/automatic translate?

### ISSUE THREAD

**Issue by privacyguy123** [shana0440/inline-translator#2]
Hey man, awesome addon. Do you plan on uploading the updated versions on to the FireFox store and possibly adding an automatic option? Failing that perhaps a hotkey? :)

**Comment by shana0440** [comment]
@privacyguy123 Hi, automatic translate can easily hit the rate limit of translate API, so I add hotkey instead, you can download it on firefox store now, if there have any problems, please let me know, thanks.
